name: Update WTI Prices

on:
  schedule:
    - cron: '30 22 * * 1-5'  # from monday to friday 22:30 ITA
workflow_dispatch: {}  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("quantmod", "ggplot2"))'

      - name: Run R script
        run: Rscript WTI_update.R

- name: Commit and push updates
  run: |
    git config --global user.email "actions@github.com"
    git config --global user.name "GitHub Actions"
    git add .
    git diff --cached --quiet || git commit -m "Auto-update WTI data"
    git push

